version: 2
updates:
  # Maintain Dockerfile base image LateX toolchain
  - package-ecosystem: "docker"
    directory: "/images/toolchain-latex"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/toolchain-quarto"
    schedule:
      interval: "weekly"

  # Maintain GitHub Actions in the workflow
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"